package dto;
// Generated Mar 12, 2019 4:39:08 AM by Hibernate Tools 4.3.1

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Tire generated by hbm2java
 */
@XmlRootElement(name = "Tire")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name="Tire", propOrder = {
    "name",
    "brand",
    "size",
    "price",
    "isValidate",
    "imgUrl"
})
public class Tire implements java.io.Serializable {

    @XmlAttribute(name = "xmlns")
    private String xmlns = "http://www.netbeans.org/schema/Tire";

    @XmlAttribute(name = "xmlns:xsi")
    private String xsi = "http://www.w3.org/2001/XMLSchema-instance";

    @XmlAttribute(name = "xsi:schemaLocation")
    private String schemaLocation = "http://www.netbeans.org/schema/Tire ../web/schema/tire.xsd";

    @XmlAttribute(name="Id")
    private long id;
    
    @XmlElement(name = "Name")
    private String name;
    
    @XmlElement(name = "Brand")
    private String brand;
    
    @XmlElement(name = "Size")
    private String size;
    
    @XmlElement(name = "Price")
    private String price;
    
    @XmlElement(name = "IsValidate")
    private Boolean isValidate;
    
    @XmlElement(name = "ImgUrl")
    private String imgUrl;

    public Tire() {
    }

    public Tire(int id) {
        this.id = id;
    }

    public Tire(long id, String name, String brand, String size, String price, Boolean isValidate, String imgUrl) {
        this.id = id;
        this.name = name;
        this.brand = brand;
        this.size = size;
        this.price = price;
        this.isValidate = isValidate;
        this.imgUrl = imgUrl;
    }
    
    public Tire( String name, String brand, String size, String price, Boolean isValidate, String imgUrl) {
        this.name = name;
        this.brand = brand;
        this.size = size;
        this.price = price;
        this.isValidate = isValidate;
        this.imgUrl = imgUrl;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getBrand() {
        return this.brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public String getSize() {
        return this.size;
    }

    public void setSize(String size) {
        this.size = size;
    }

    public String getPrice() {
        return this.price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public Boolean getIsValidate() {
        return this.isValidate;
    }

    public void setIsValidate(Boolean isValidate) {
        this.isValidate = isValidate;
    }

    public String getImgUrl() {
        return this.imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

}
